### ISSUE TITLE
Game sometimes crashes on start

### ISSUE THREAD

**Issue by its-danny** [dannytatom/xibalba#46]
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: sprites/qbicfeet_10x10.atlas
        at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:136)
        at me.dannytatom.xibalba.screens.LoadingScreen.render(LoadingScreen.java:62)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by ycros** [comment]
I might have fixed this in #47
